### ISSUE TITLE
`clj -T` not mentioned in README

### ISSUE THREAD

**Issue by mortenschioler** [clojure/tools.deps.graph#10]
Funnily, tools.deps.graph is mentioned in https://clojure.org/reference/deps_and_cli#_help_functions as an example of a library that is  well-suited for use as a proper "tool" in clj. So I'm wondering: Why are those same instructions not included here? Have you guys abandoned advocating the use of `-T`? I think it works quite well and would like to see more widespread adoption.

**Comment by puredanger** [comment]
Added
