### ISSUE TITLE
Instructions for adding to ~/.clojure/deps.edn are wrong

### ISSUE THREAD

**Issue by stathissideris** [clojure/tools.deps.graph#3]
The instructions say that you should add an alias with a `:deps` key in ~/.clojure/deps.edn when it should be `:extra-deps`.

**Comment by puredanger** [comment]
:deps is correct - this key in an alias says to replace the project deps with the tool deps. This is a newer feature (added in clj 1.10.1.) - if you're seeing an error, upgrade your `clj` tool to latest.

**Comment by stathissideris** [comment]
Many thanks, I didn't know about this!
