### ISSUE TITLE
Error building classpath in README example

### ISSUE THREAD

**Issue by usernolan** [clojure/tools.deps.graph#5]
It's trivial to identify and fix, but just in case it hasn't been raised elsewhere: the README prescribes putting `:deps` into an alias (instead of `:extra-deps`), which throws

```
Error building classpath. Unknown alias key: :deps
```

OTOH: Epic error message! Thank you for this tool 🙏. The holidays came early!

**Comment by pedrorgirardi** [comment]
Hi @Nolan330 , `:deps` is correct. Please see #3 .

**Comment by usernolan** [comment]
@pedrorgirardi Thank you for the info! I suppose I should have known better than to assume this was an oversight.
