### ISSUE TITLE
Problem installing graph tools for invalid tag

### ISSUE THREAD

**Issue by RafaelCampo-ME** [clojure/tools.deps.graph#9]
Hi

I'm trying to install graph using the following command: 

` clj -Ttools install io.github.clojure/tools.deps.graph '{:git/tag "v1.0.63"}' :as deps-graph`

But I get this error: 

`Library io.github.clojure/tools.deps.graph has invalid tag: v1.0.63`

Full log above

[Clojure-logs.txt](https://github.com/clojure/tools.deps.graph/files/10506194/Clojure-logs.txt)

Can please check this?

**Comment by puredanger** [comment]
Latest is v1.1.76

**Comment by raoul2000** [comment]
Hello,
it seems I have the same problem with tag v1.1.76.  I'm on a Windows 10 machine.

```
PS C:\Users\Raoul> clj -Ttools install io.github.clojure/tools.deps.graph '{:git/tag "v1.1.76"}' :as graph
Cloning: https://github.com/clojure/tools.deps.graph.git
Execution error (ExceptionInfo) at clojure.tools.deps.alpha.extensions.git/coord-err (git.clj:45).
Library io.github.clojure/tools.deps.graph has invalid tag: v1.1.76

Full report at:
C:\Users\Raoul\AppData\Local\Temp\clojure-1800455321309482971.edn
P
```

[clojure-1800455321309482971.edn](https://github.com/clojure/tools.deps.graph/files/11112084/clojure-1800455321309482971.edn.txt)

Thanks

**Comment by puredanger** [comment]
what version of the Clojure CLI (`clj --version`)?

**Comment by puredanger** [comment]
and what version of `git --version`

**Comment by puredanger** [comment]
On Windows, quoting is different (see https://clojure.org/reference/deps_and_cli#quoting for Windows specific guidance), and you may instead need to do:

```clj -Ttools install io.github.clojure/tools.deps.graph '{:git/tag """v1.1.76"""}' :as graph```

Also, fyi there is now an install-latest command if you are on a new enough version of `clj`:

```clj -Ttools install-latest :lib io.github.clojure/tools.deps.graph :as graph```

**Comment by raoul2000** [comment]
Thanks @puredanger this was indeed a quoting issue with Windows 👍
